wireapp/wire-desktop

- electron/js/menu/context.js
- electron/js/menu/custom-context.js
This PR adds a custom context module, which stops and any propagation of the 'customContextMenu' Event and replaces the web context menu with a native menu. This should replace the current conversation list menu in the near future.
> message context menu (WEBAPP-2861)

- electron/main.js
It seems like it's a bug on Electron's side https://github.com/electron/electron/issues/6954
> Full Screen on Linux fixed

- Gruntfile.coffee
- package.json
With this commit, NPM can be removed as a dependency in favour of yarn. 
How important is the `npm rebuild` command before building? 
If it is imperative to rebuild the modules before packaging, a possible solution would be to add `yarn install --force` to the shell task in the Gruntfile.
> Use yarn with Electron-Builder too

- electron/package.json
- package.json
This will also define the license for the built apps.
Currently, the deb shows an 'unknown' license.
The LICENSE.md file from the repository root (which specifies GNU GPLv3) is not included in the final packages; it really should be. Instead, the Github license is included.
> Add license info to app package.json

- package.json
While these may not be missing from a typical Ubuntu install, Wire refuses to launch without at least these dependencies. This list generated from a the official Ubuntu Docker image (very minimal) in which I installed Wire. See #171 for the particular shared library `.so` files that were missing.
> Update deb deps

- electron/js/menu/system.js
- electron/js/squirrel.js
- electron/main.js
No need for the #229.. it works because of this line: https://github.com/wireapp/wire-desktop/blob/master/electron/locale/locale.js#L64
Test it by deleting the `init.json` file.
(macOS: `~/Library/Application Support/Wire/init.json`)
> Get user's locale on first run

- electron/js/menu/context.js
As of today, when spelling is not configured in init.json, the spell check is not working. 
However in this special case the checkbox "Check Spelling while typing" is enabled, implying that the spell check _should work_. But it doesn't.
The intention obviously was to make spell check enabled by default, but it never worked.
This pull request fixes the checkbox state, so that it isn't misleading anymore. This preserves the current behavior of the app.
If you want to enable spell check by default, it can be achieved with the code below. I didn't do it as it would be a breaking change, people will suddenly start seeing a spell check when it wasn't there before. 
If you still want me to do it, suggest me where to place this code better, and I will do update this pull request. Ideally it …
> Fix spelling checkbox state in system menu

- package.json
Just doing as I'm told :wink: 
``` shell
$ node_modules/.bin/build --linux --x64 --dir
⚠️  "directories" in the root is deprecated, please specify in the "build"
Rebuilding native production dependencies for linux:x64
Packaging for linux x64 using electron 1.4.14 to wrap/dist/linux-unpacked
```
> Move `directories` under `build`

- electron/js/menu/system.js
- electron/main.js
Sorry, this probably should have been included in #154, but when I wrote that PR, I had already implemented #146 locally, so I didn't think to implement this. Anyway, as of https://github.com/wireapp/wire-desktop/commit/891a5c5ae49245bd492b4047d9744cf43cf88d22, the app will launch with a window at startup. This PR will make the app start in the tray.
I thought about changing the windows argument from `--startup` to `--hidden`, but I wasn't sure where the argument is defined. We could also use the argument `--startup` on the Linux launcher, but only once https://github.com/Teamwork/node-auto-launch/pull/47 is merged.
EDIT: This PR replaces #146, or vice-versa.
> Linux autostart start minimized

- electron/js/menu/developer.js
- electron/js/menu/system.js
- electron/js/window-manager.js
- electron/main.js
I have seen electron actions performed in the BrowserWindow fails because the currently we rely on the focussed window. Sometimes focus is on the about screen or devtools and actions thus fail resulting in errors.
This should be safe in the menu cases but I temporarly reused the code when making changes to the updater and came across this problem. This can be handled in a more robust way. I am thus disclosing the window ID of the main BrowserWindow and retrieve it based on the ID instead of focus.
> Preferably retrieve BrowserWindow by ID

- package.json
This is a temporary workaround for atom/node-spellchecker#49, as suggested by @ConorIA in #334. 
I confirm that it does fix the issue.
Disabling only for Linux since the original bug describes this as a Linux-only issue, though I didn't verify this.
> Disable asar for Linux

- electron/main.js
- package.json
electron recently changed the the `setCertificateVerifyProc`api. so in order to update to 1.6.1 we need update the certificate verification code on our side.
see: https://github.com/electron/electron/blob/master/docs/api/session.md#sessetcertificateverifyprocproc
> Bump electron version

- electron/js/menu/system.js
- electron/main.js
https://electron.atom.io/docs/api/app/#apprelaunchoptions
According to electron docs 'app.quit' should be called AFTER 'app.relaunch'
> Call 'app.quit()' after 'app.relaunch()'

- electron/js/menu/system.js
- electron/locale/strings-en.js
- electron/locale/strings.js
- electron/main.js
A couple of questions here: 
1. Should the menu item be a check box?
2. Should the menu item be changed to "Hide the menu bar by default"?
As it stands now, a user might choose to hide them menu bar. If that user hits 'Alt', the user *might* think that the menu bar will now remain visible, however it will disappear again on restart, unless the user remembers to click on the "Show/Hide Menu Bar" item again. Maybe this isn't intuitive.
> Make the preference to hide the menu sticky

- bin/win-prod-s3-deploy.py
- bin/win-prod-s3.py
- bin/win-s3-deploy.py
- bin/win-s3.py
* Both production and internal script now work the same. The s3 internal script does not upload RELEASES file directly. Instead this is now done by the deploy script (like on production).
* Fixed issue with environment variables when using client instead of resource client object on boto3 (tested with internal already)
> Update windows deploy scripts

- bin/deb/after-install.tpl
- bin/deb/after-remove.tpl
A [change on the `electron-builder` side](https://github.com/electron-userland/electron-builder/commit/fe137fc221f46683433cc7dc86984caeab281d84) broke the `after-install.tpl` and `after-remove.tpl` scripts. This resolves #602, but the bad links might still exist for some users.
> Fix debian pre/post-install scripts

- electron/package.json
This enables MSVC and updates `neon` in `libsodium-neon`.
> Update libsodium-neon to 2.1.0

- electron/package.json
- electron/rebuild-native-modules.js
- package.json
* When we rebuild native modules, we can now set the target architecture with the environment variable `wire_target_arch`.
* Updated `electron-rebuild`.
> Easier rebuild of native modules

- Gruntfile.coffee
This updates electron-packager config to use camel case properties since the old way is deprecated. I removed 'dev-version' since its not longer used by the packager and 'min-version' since its already set.
> update electron-packager config

- Gruntfile.coffee
- README.md
Currently, the 'bundle' task is missing from the README. 
I thought to send a PR to update the README, but it occurred to me that this might be easier for end-users to get their heads around.
> Make custom Linux builds easier

- Gruntfile.coffee
- electron/package.json
- info.json
- linux.Jenkinsfile
- macOS.Jenkinsfile
- package.json
- windows.Jenkinsfile
This PR will use the build number of the job and include it into the version number. The version number will now also tell us when a build was compiled for internal or manually
**Production builds** will look like this:
`2.15.2801`
**Internal builds** will look like this:
`2.15.2801-internal`
**Manually compiled builds** will include the commit id (short SHA) of the last commit (the build number will be always 0 because no CI was used):
`2.15.0-5df6b7c`
or
`2.15.0-5df6b7c-internal`
To bump the major.minor part of the version number, you can use the grunt task:
`grunt bump-version`
In this case it would bump the version from `2.15` to `2.16`.
> Use build id from Jenkins CI jobs in version number

- Gruntfile.coffee
Simplifies AUR package `wire-desktop-beta`.
Append `?w=1` to URL before reviewing the code: [click](https://github.com/wireapp/wire-desktop/pull/987/files?w=1)
Reference: #986
> Add `linux-other-internal` Grunt task

- Gruntfile.js
This will create the entry `StartupWMClass=Wire` in the .desktop file and fixes a range of issues regarding duplicated icons in gnome-shell.
> Fix duplicated icons in gnome-shell dock

- windows.Jenkinsfile
Most linker issues in the rust compilation were fixed by setting the Visual Studio development environment with VsDevCmd.bat.
The remaining conflict between the node module machine type and the target machine type was solved by using the x86 version of node.
> fix: Compile libsodium-neon with correct x86 linker and module version on Windows

- Gruntfile.js
- `.desktop` spec is updated to version 1.1
- adds keywords and generic name
- uses standard category names
- uses "Wire" as application menu name, not `wire-desktop`
```
[Desktop Entry]
Name=Wire
Comment=Secure messenger for everyone.
Exec="/opt/wire-desktop/wire-desktop" %U
Terminal=false
Type=Application
Icon=wire-desktop
Version=1.1
GenericName=Privacy-Oriented Messenger
Keywords=chat;encrypt;e2e;messenger;videocall
StartupWMClass=Wire
Categories=Network;InstantMessaging;Chat;VideoConference;
```
Edit: I would like developer input re: [keywords, GenericName](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html), and [Categories](https://specifications.freedesktop.org/menu-spec/latest/apa.html#main-category-registry) …
> Create a better .desktop file

- electron/js/menu/context.js
In addition to https://github.com/wireapp/wire-webapp/pull/1957.
> [WEBAPP-4491] fix: Strip mailto: from copied links

- electron/package-lock.json
- electron/package.json
- package-lock.json
`node-rebuild` was used for `libsodium-neon` and `node-addressbook` is building itself already [after installing](https://github.com/wireapp/node-addressbook/blob/master/package.json#L33).
> fix: Don't rebuild twice

- Gruntfile.js
maybe @gregor should confirm that the `hostnameShouldBePinned` wasn't supposed to go anywhere else
> fix Gruntfile

- electron/js/preload.js
- electron/renderer/static/webview-preload.js
Default zoom level is 0 not 1. Since we added boundaries for both visual and layout values, these have to be 0. Also disables zooming by pinch.
https://electronjs.org/docs/api/web-frame#webframesetzoomlevellevel
> fix: Set appropriate zoom levels

- electron/main.js
See https://github.com/electron/electron/commit/594302fcff2311c95a576bd6ac432987aadbcb1e#diff-b0dbfed07f681b0f2ecb1eb01f0ed85b
> fix: option to hide title bar was changed to camel case in electron 2.0.0

- electron/js/menu/tray.js
I looked into why #1599 happens. The code is set to enable the urgency hint if the "unread" count is greater than the previously known count:
https://github.com/wireapp/wire-desktop/blob/baaf586911d044e3a23990d43b41e8a129cbcc7a/electron/js/menu/tray.js#L70
However, the `count` here is **not** the number of unread messages, instead it equals to the [number of _conversations_ that have unread messages](https://github.com/wireapp/wire-webapp/blob/d6ce31b0c39760291d56042dafd52e19b80fd6ba/app/script/view_model/WindowTitleViewModel.js#L65).
So, if one person sends you the first message while Wire is unfocused, you have 1 conversation with unread messages, `lastUnreadCount` is 0, 1 is greater than 0 so the urgency hint is set, and `lastUnreadCount` is now 1. When the same person sends you …
> Fix premature unset of urgency hint

- linux.Jenkinsfile
- macOS.Jenkinsfile
- windows.Jenkinsfile
This PR will
* let Jenkins use Node.js 8.11.3
* use `npx` instead of installing `grunt` globally.
* always use the latest version of `npm`.
> chore: Update Node.js to 8.11.3

- electron/js/menu/tray.js
This is an improvement on top of #1610.
The logic in `master` is: once we get at least one unread conversation, mark Wire as "urgent" until Wire is focused again.
This PR extends the logic to: once we get at least one unread conversation, mark Wire as "urgent" until Wire is focused again _or all conversations are read on another device_.
The idea is: I might leave my laptop and continue discussion on the phone, once I get back to my laptop I don't want to see Wire marked as "urgent" in case I have already replied to all the messages from the phone. But if there are some messages that I haven't replied from the phone, I do want to see Wire marked as "urgent", so I can remember to reply to people.
> feat: Remove urgency hint when messages are read on other device

- electron/js/lib/openGraph.js
Previous strategy was:
- do HEAD request and read the content of the response ;
- if the content type doesn't match throw error ;
- else send another request via `openGraph`.
New strategy:
- do full request ;
- when the headers arrive (before any content is downloaded), check that `content-type` is of type `text/html` ;
- start counting downloaded bytes ;
- if the number of bytes exceed the limit, we fail ;
- if not we call the `parse` method of `openGraph` only on the `<head>` of the document.
> fix: Limit content length size when downloading link preview (WEBAPP-4422, WEBAPP-5341)

- Gruntfile.js
This PR will
* partly revert https://github.com/wireapp/wire-desktop/commit/49feee08bc3882d0b47308c6393897ecb5bfad50 where `fpm` settings were moved to the wrong part of the Gruntfile. Now the Debian package names are "wire-desktop" and "wire-desktop-internal".
(e.g.: a user can run `sudo apt-get install wire-desktop`)
* set `executableName` to "wire-desktop" and "wire-desktop-internal" instead of "wire" and "wireinternal".
(e.g.: a user can run `/opt/wire-desktop/wire-desktop`).
> fix: Linux executable name

- electron/js/settings/SchemaUpdater.js
- electron/main.js
We always run the config schema updates on app start (similar to IndexedDB schema updates on webapp). When there is an old config (`./init.json`), then we update that config and save it to its new place (`./config/init.json`).
The problem here was, that no config change was detected (because wrapper was already running on latest config) and thus the config update was skipped BUT the config save wasn't skipped so a properly updated config was overwritten on the harddisk with a config template which includes nothing except:
```json
{
"configVersion": 1
}
```
That's why the `locale` property got overwritten.
During testing I realized that it can happen that log file renaming fails (because log file is opened in Notepad++ or still written into). This can cause a JavaScript error and crash of …
> fix: Change app language (WEBAPP-5451)

- Gruntfile.js
* This fixes #1735 by removing keys from the `linux` settings which don't belong there.
* The `Version` entry in a Gnome desktop file actually specifies the version of the Desktop Entry Specification, not the product version, see https://developer.gnome.org/desktop-entry-spec/.
> fix: Remove invalid settings from Gruntfile

- electron/package.json
- package.json
`husky` 1.0.0 has changed the way of adding precommit hooks. See https://github.com/typicode/husky#upgrading-from-014.
Follow-up to https://github.com/wireapp/wire-web-packages/pull/1162.
> fix: Add new husky precommit hook

- Gruntfile.js
- tsconfig.json
This PR will
* set the correct path for the config file used by Grunt
* ignore the `wrap` folder when building
> fix: Building with TypeScript

- electron/src/js/menu/system.ts
https://github.com/electron/electron/issues/15728
> fix: Make Undo/Redo disappear on macOS

- electron/renderer/src/components/Webviews.jsx
- electron/src/js/environment.ts
- electron/src/main.ts
- package.json
The port and directory for serving the webapp from localhost changed with https://github.com/wireapp/wire-webapp/pull/4946.
> fix: New localhost port and dir

- package.json
`prestart` is automatically run when running `start` .
> fix: Don't run prestart twice

- electron/src/menu/system.ts
Because this is a duplicate of 'Edit / Preferences' which is the typical location for Linux apps.
Signed-off-by: Volker Theile <votdev@gmx.de>
> Remove 'Wire / Preferences' menu on Linux

- electron/renderer/src/components/Webviews.jsx
- electron/src/main.ts
This reverts #2004 and uses the initial approach (https://github.com/wireapp/wire-desktop/pull/2004/commits/a503f72ad913a9e5e29e5fadf27f03d71351f79d).
> fix: Preload script

- electron/src/main.ts
This fixes https://github.com/wireapp/wire-desktop/issues/2046.
> fix: Unregister global shortcuts on close event

- electron/src/menu/system.ts
After https://github.com/wireapp/wire-webapp/pull/5574 is released, we can enable the PageDown/Up buttons again.
> fix: Re-enable PageDown/Up buttons

- Gruntfile.js
- electron/renderer/src/actions/index.js
- electron/renderer/src/components/Webviews.jsx
- electron/renderer/src/containers/WebviewsContainer.js
- electron/renderer/src/reducers/accountReducer.js
- electron/renderer/static/webview-preload.js
Reset identity (userId, teamId and isAdding on true) when logging out without deleting data. This allows SSO link to work properly when there is three accounts and one of them is logged out.
> Reset identity when logging out without deleting data (WEBAPP-5921)

- bin/linux-checksums.sh
This PR will
* fix the directory name inside the archive signature for releases
> fix: Archive signature dir name

- Gruntfile.js
This makes building easier for developers who don't bundle Electron into the app directly (no behavior changed for us).
> chore: Split up linux-prod task

- Gruntfile.js
- README.md
- bin/linux-prod-s3.py
- bin/repo/conf/apt-ftparchive.conf
- bin/repo/conf/stable.conf
- bin/repo/linux-prod-repo.sh
- jenkins/linux.groovy
See the official announcement from Electron: [Discontinuing support for 32-bit Linux](https://electronjs.org/blog/linux-32bit-support).
> chore: Remove 32-bit support for Linux

- Gruntfile.js
No functional changes, repeating #2228 for other linux tasks. I only need it for internal (for wire-desktop-beta), but thought why not align all linux tasks at once while I'm at it.
> chore: Split other Linux build tasks as well

- electron/src/js/squirrel.ts
- jenkins/windows.groovy
Squirrel's updater/installer was renamed from `Update.exe` to `Squirrel.exe`.
See https://github.com/electron/windows-installer/pull/288#issuecomment-468430461
> runfix: Update.exe is now Squirrel.exe

- electron/package.json
- electron/yarn.lock
`debug` is still used in [`ConfigurationPersistence.ts`](https://github.com/wireapp/wire-desktop/blob/6233186a5df75c4708bb2b8c8bb790f4f779d58c/electron/src/settings/ConfigurationPersistence.ts) and [`SchemaUpdater.ts`](https://github.com/wireapp/wire-desktop/blob/6233186a5df75c4708bb2b8c8bb790f4f779d58c/electron/src/settings/SchemaUpdater.ts).
> fix: Add missing debug dependency

- electron/package.json
- electron/yarn.lock
- package.json
- yarn.lock
This PR will
* remove `cross-spawn` and `commander` which are left over from old features and are not in use anymore.
> chore: Remove unneeded dependencies

- electron/src/interfaces/locale.ts
- electron/src/menu/system.ts
See [en-US.json#L62](https://github.com/wireapp/wire-web-config-wire/blob/master/wire-desktop/content/translation/en-US.json#L62).
> runfix: Load correct string for website menu item

- electron/src/window/AboutWindow.ts
Best viewed [without whitespace changes](https://github.com/wireapp/wire-desktop/pull/2411/files?w=1).
No behavior was changed.
> refactor: Cleanup AboutWindow

- electron/src/sso/SingleSignOn.test.main.ts
- package.json
- tsconfig.jest.json
- yarn.lock
Follow-up to https://github.com/wireapp/wire-desktop/pull/2417.
Without an additional `tsconfig.json` file it was not possible to lint the test files and my IDE was throwing errors because `lint-staged` was trying to lint them on commit.
> chore: Add additional config file for TS tests

- electron/package.json
- electron/src/interfaces/global.ts
- electron/src/interfaces/locale.ts
- electron/src/interfaces/main.ts
- electron/src/interfaces/polyfills.ts
- electron/src/locale/locale.ts
- electron/src/window/AboutWindow.ts
- package.json
- yarn.lock
This PR will
* add `productName` to `electron/package.json` following https://github.com/wireapp/wire-desktop-packages/pull/450
* replace `{[key: string]: string}`-like interfaces with TypeScript's built-in `Record` type
* remove locale string replacements (which were used to replace e.g. `{{appName}}` in locale strings, but we never used that)
* set all object keys to required in locale objects as there are no missing keys anymore due to automatic synchronizing in our config repositories
> fix: locale replacement, productName, Record (WEBAPP-6106)

- .copyconfigrc.js
Otherwise builds with completely different config repos set via [`WIRE_CONFIGURATION_REPOSITORY`](https://github.com/wireapp/wire-web-packages/blob/master/packages/copy-config/README.md#environment-variables) will never copy the correct files but always the default files.
This partly reverts https://github.com/wireapp/wire-desktop/pull/2512.
> runfix: Don't copy config files from node_modules

- package.json
- yarn.lock
This one was not caught by dependabot since it wanted to update to 5.0.0 directly.
> chore(deps-dev): bump electron to 4.1.5

- electron/renderer/src/components/Sidebar.jsx
`z` was not defined since the WebApp was not loaded yet. We switch to strings for the time being.
See [`UserPermission.js#L135`](https://github.com/wireapp/wire-webapp/blob/68a81692b7ecf1bd1e4b5339f72a65d65a06297a/src/script/user/UserPermission.js#L135)
> fix: Right-click in sidebar (WEBAPP-6251)

- electron/src/main.ts
Seems like the hardware acceleration issue was fixed: https://github.com/electron/electron/issues/13415
This closes https://github.com/wireapp/wire-desktop/issues/2758.
> feat: Re-enable hardware acceleration on Linux

- electron/renderer/src/components/App.jsx
- yarn.lock
This fixes a missing import which was introduced in https://github.com/wireapp/wire-desktop/pull/2547.
> fix: Import config to App (WEBAPP-6279)

- .travis.yml
Recently, builds on macOS [failed](https://travis-ci.org/wireapp/wire-desktop/jobs/555605515#L151) with the error
```
g++-4.9: error: unrecognized command line option '-stdlib=libc++'
```
while building `node-addressbook`. So we are using now clang instead of g++ on macOS builds.
> fix: Use clang for Travis on macOS

- jenkins/macOS.groovy
- jenkins/windows.groovy
We swallowed the error when the smoke run can not be triggered
> chore: Print actual error in Jenkins console

- electron/src/main.ts
- electron/src/menu/TrayHandler.ts
- electron/src/runtime/EnvironmentUtil.ts
Probable fix for https://github.com/wireapp/wire-desktop/issues/957.
> fix: Use Gnome icon only on X11

- electron/src/menu/system.ts
This got lost during the refactor in https://github.com/wireapp/wire-desktop/pull/2846.
> fix: macOS quit shortcut (WEBAPP-6358)

- electron/src/lib/openGraph.ts
A website consisting only of 
```html
<head>
<meta property="og:image" content="http://example.com/image.jpg">
```
is technically not valid HTML5 **but** it has a preview image. Browsers will also display it correctly.
> fix: Create link previews for websites with invalid head (WEBAPP-6278)

- bin/deb/after-install.tpl
This helps with https://github.com/electron/electron/issues/17972 on Linux machines not being able to run Wire with Electron 5 after installation.
> fix: Permissions for Chrome sandbox on Linux

- electron/src/main.ts
- package.json
Because of https://github.com/electron/electron/issues/17972 starting the app on Linux machines always returns the error "The SUID sandbox helper binary was found, but is not configured correctly. [...]".
> chore: Start without sandbox, reuse variable

- electron/src/lib/openGraph.ts
Finding a regex match in a large website is very costly and can take a long time. Since open-graph [uses cheerio](https://github.com/samholmes/node-open-graph/blob/master/index.js#L59) to parse the content, it's much faster. As a result we will just send the whole body to open-graph instead of trying to parse it ourselves.
> fix: Speed up link preview generation (WEBAPP-6415)

- electron/renderer/static/webview-preload.js
- electron/src/lib/CertificateVerifyProcManager.ts
- electron/src/lib/CoreProtocol.ts
- electron/src/lib/LocalAccountDeletion.ts
- electron/src/lib/openGraph.ts
- electron/src/main.ts
- electron/src/renderer/preload.ts
- electron/src/settings/SchemaUpdater.ts
- electron/src/update/Squirrel.ts
Currently the logs look like this:
```
@wireapp/desktop//Users/<username>/git/wire-desktop/electron/renderer/static/webview-preload.js [2019-09-10 15:42:31] <some message>
```
But they should look like this:
```
@wireapp/desktop/webview-preload.js [2019-09-10 15:42:31] <some message>
```
> fix: Log with filename only

- electron/src/lib/openGraph.ts
Backported https://github.com/wireapp/wire-desktop/pull/3126 to Electron 4.
> fix: Send a link preview even without image (WEBAPP-6082) (backport)

- electron/src/sso/SingleSignOn.ts
Backported https://github.com/wireapp/wire-desktop/pull/2956 to Electron 4.
> fix: Register SSO protocol only once (WEBAPP-6372) (backport)

- electron/renderer/static/webview-preload.js
- electron/src/lib/openGraph.ts
This removes `window.openGraph` which was in use by the WebApp but is already replaced by `window.openGraphAsync` for 8 months.
> fix: Don't send link previews without metadata, remove synchronous openGraph (WEBAPP-6508)

- electron/renderer/static/webview-preload.js
- electron/src/lib/openGraph.ts
Backported https://github.com/wireapp/wire-desktop/pull/3158 to Electron 4.
> fix: Don't send link previews without metadata, remove synchronous openGraph (WEBAPP-6508) (backport)

- electron/src/main.ts
Backported https://github.com/wireapp/wire-desktop/pull/3094 to Electron 4.
> fix: Portable path (backport)

- electron/src/main.ts
- electron/src/menu/developer.ts
- electron/src/menu/system.ts
- electron/src/runtime/lifecycle.ts
The trick here is to create an invisible menu item with an accelerator (the shortcut) which will act as a local shortcut. See [Local Shortcuts](https://github.com/electron/electron/blob/v5.0.12/docs/tutorial/keyboard-shortcuts.md#local-shortcuts).
This fixes https://github.com/wireapp/wire-desktop/issues/2577.
> fix: Avoid global shortcuts

- bin/build-tools/lib/build-linux.ts
This fixes https://github.com/wireapp/wire-desktop/issues/2648.
> fix(build-tools): Don't ask to integrate AppImage

- electron/src/main.ts
- electron/src/menu/system.ts
This re-enables global shortcuts for macOS since the trick from https://github.com/wireapp/wire-desktop/pull/3207 doesn't work here.
> runfix: Re-enable global shortcuts for macOS (WEBAPP-6528)

- electron/src/main.ts
- electron/src/window/AboutWindow.ts
- electron/src/window/ProxyPromptWindow.ts
See Electron Docs: "[Do Not Use `enableBlinkFeatures`](https://github.com/electron/electron/blob/master/docs/tutorial/security.md#9-do-not-use-enableblinkfeatures)".
The docs recommend to not use `enableBlinkFeatures` at all but then the console log tells me:
```
"Electron Security Warning (enableBlinkFeatures) font-weight: bold; This renderer process has additional "enableBlinkFeatures"
enabled. This exposes users of this app to some security risk. If you do not
need this feature, you should disable it.
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged."
```
> fix: Disable Blink features

- babel.config.js
- package.json
- tsconfig.json
- yarn.lock
Since Electron 7.1.3 is based on Chrome 78, we can also build for this version.
> refactor: Build for ES6 and Chrome 78

- bin/bin-utils.ts
- bin/build-tools/lib/build-macos.ts
- bin/build-tools/lib/commonConfig.ts
- bin/deploy-tools/github-draft-cli.ts
If the directory is not a git repository (e.g. downloaded as an archive), all `git` commands fail and the app is not built.
> chore: Build app without git

- jenkins/macOS.groovy
This fixes issues with certain passwords. Already tested with the last build on macOS production job.
> build: macOS keychain password may contain special characters

- electron/src/main.ts
- electron/src/runtime/lifecycle.ts
Reverts wireapp/wire-desktop#3482
> Revert "fix: Use single instance lock instead of variable"

- electron/renderer/src/actions/index.js
- electron/renderer/src/reducers/accountReducer.js
This fixes https://github.com/wireapp/wire-desktop/issues/3763.
The import for `uuid` 7.x changed, see https://github.com/uuidjs/uuid/blob/master/CHANGELOG.md#700-2020-02-24 and https://github.com/uuidjs/uuid#create-version-4-random-uuids.
> runfix: Import uuid 7.x

- electron/src/lib/LocalAccountDeletion.ts
- electron/src/main.ts
- electron/src/menu/TrayHandler.ts
- electron/src/runtime/lifecycle.ts
- electron/src/update/squirrel.ts
> fix: Don't check twice for single instance (WEBAPP-6663)

- electron/src/interfaces/locale.ts
- electron/src/main.ts
- electron/src/menu/system.ts
- electron/src/settings/SettingsType.ts
- package.json
- yarn.lock
> feat: Add menu entry to toggle spell checking

- electron/src/menu/TrayHandler.ts
This PR will let the app only update the tray icon if the number of unread messages is different from before (e.g. on an incoming message in a muted group the counter doesn't change but the tray icon change gets triggered).
> fix: Don't flicker tray icon on incoming messages

- electron/src/lib/ElectronUtil.ts
- electron/src/menu/developer.ts
- electron/src/sso/SingleSignOn.ts
This removes all trailing `;` and adds `;0` at the end of JS snippets which are to be executed on a `webContent` to ensure the resulting value of `executeJavaScript()` is not used. See https://github.com/electron/electron/issues/23722.
I could not make use of the util function in the SSO preload, but this area will be improved soon.
> fix: Don't use result of executeJavaScript (WEBAPP-7090)

- electron/renderer/src/components/LoadingSpinner.css
- electron/renderer/src/components/LoadingSpinner.jsx
Since we removed only the `FlexBox` and the Loading Spinner itself after the page is loaded, we had a left-over element over the whole interface which rendered the app useless :slightly_smiling_face:
> runfix: Use opacity instead of TransitionContainer on the LoadingSpinner

- electron/src/lib/openGraph.ts
- electron/src/runtime/OriginValidator.ts
- electron/src/window/WindowUtil.ts
`URL.parse()` is [deprecated](https://nodejs.org/docs/latest-v12.x/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost).
> refactor: new URL instead of URL.parse

- electron/src/main.ts
- electron/src/settings/config.ts
- electron/src/update/squirrel.ts
This fixes https://github.com/wireapp/wire-desktop/issues/4160.
> fix: Create shortcuts manually to re-enable clickable notifications (SQCORE-544)

- electron/renderer/src/components/LoadingSpinner.css
- electron/renderer/src/components/LoadingSpinner.jsx
This pull request attempts to reduce Wire's CPU usage when idle.
In the discussions related to issues #2507 and #2239 (and maybe elsewhere) @charlag et al. tracked down a culprit for some surpsingly high constant CPU load. The LoadingSpinner component is always rendered on top of the rest of the UI with 0 opacity after it has initially faded out, continuously using resources.
This pull request addresses the issue ~~by hooking to the `onTransitionEnd` and `onTransitionCanceled` events and set a flag marking the fade out completed~~ giving the fade out transition a fixed amount of time to finish. After this the component returns `null`, effectively removing the LoadingSpinner contents from the DOM tree.
Personally, I've noticed constant ~15% load when Wire was idling on my M1 MacBook Air. …
> fix: Don't render LoadingSpinner after it has faded out

- electron/src/menu/system.ts
This should prevent people from being bombarded by accidental pings. Whilst a useful feature, having it bound to a shortcut, even more so one that's commonly used by other apps for non-intrusive behaviour, leads to a lot of frustrating accidental triggers.
----
---- …
> Removed ping keyboard shorcut.

- .github/dependabot.yml
Dependabot is not notifying about new electron updates.
Update dependabot config to use currently used electron version.
> chore: Bump electron version in dependabot config (SQSERVICES-1490)

- jenkins/deployment.groovy
- jenkins/macOS.groovy
_No masters, no slaves_
The word "master" is being retired as the term for the main Jenkins process and the built-in node. The built-in node is called just "built-in node" with the label "built-in" instead of the label "master".
The current version of Jenkins still understands the label "master" but in future versions this will be probably removed. The PR replaces all usages of "master" node.
> chore: replace master with built-in label for Jenkins pipeline

- README.md
This is a recreation of #5271 
The reason was that #5271 was based on the wrong branch after some branching changes were done on the current repo.
> [chore] add yarn installation instructions

- electron/renderer/src/components/Webview.jsx
- electron/src/preload/preload-webview.ts
----
----
This PR adds support for sidebar theme change from external (other) client what didn't work previously. Sidebar theme was updated only when changed from inside electron app, it did not react to remote changes.
We listen for properties update event (`WebAppEvents.PROPERTIES.UPDATED`), read `theme` field form update object and pass it to electron's redux reducer which will update sidebar theme accordingly (only if it's different from previous state).
Before
After:
----
----
----
> runfix: add external theme update support for sidebar (ACC-199)

- electron/src/menu/system.ts
This PR temporarily removes broken links from the desktop menu. 
The goal would be to have the wire website updated to add these back eventually. 
Until then, the legal link will direct to a location where the other two are accessible.
> fix: remove dead links from menu (SQCORE-1271)

- electron/src/preload/preload-webview.ts
> runfix: use base64 encoding for key encryption [FS-1083]

- electron/src/global.ts
- electron/src/preload/preload-webview.ts
----
----
We want to add backward compatibility for the clients that were broken after mistakenly enabling `FEATURE_ENABLE_MLS` flag on their environment. We want to disable MLS for these clients. 
The (a little bit hacky) solution is to rename electron's `secretsCrypto` global config to `systemCrypto` and then on the `webapp` side, check if a current client is using desktop wrapper and the new global is defined and enable MLS only in this case.
----
----
> runfix: rename secretsCrypto to support broken clients [FS-1083]

- electron/renderer/src/components/Sidebar.jsx
- electron/renderer/src/components/Webview.jsx
- electron/renderer/src/components/context/ContextMenu.css
- electron/renderer/src/lib/keyboardUtil.js
----
- [wire-desktop] Keyboard navigation can move focus into second account invisible settings
- keyboard navigation from ephemeral button(chat message actions) should focus on the account sidebar
- make accounts sidebar keyboard accessible
- accounts can be opened using keyboard(enter key)
- trap the focus in sidebar accounts
- add account button should be tabbed and focusable
- add account can be opened using keyboard
----
> fix: [wire-desktop] Keyboard navigation can move focus into second account invisible settings(ACC-393)

- electron/src/main.ts
- electron/src/runtime/EnvironmentUtil.ts
- package.json
- localhost should not be used as a development environment anymore and local.zinfra.io is used instead
- the CORS bypass in `main.ts` is not necessary
- replace the localhost option by localzinfra
- remove the 2 scripts using localhost from `package.json`
- remove the CORS bypass entirely
- fix the broken start script in `package.json` by wrapping `@wireapp*` in single quotes
> fix: replace localhost environment option by localzinfra

- electron/src/update/shortcuts.ts
- electron/src/update/squirrel.ts
Since https://github.com/wireapp/wire-desktop/pull/4965 we manually create the shortcuts to the application exec file. 
But because those shortcuts are based on the current `process.execPath` that resolves to the versioned exec file, we get shortcuts that link to a version that might at some point be an old version. 
We now use the root level `Wire.exe` file as the link target
> fix(windows): Feed root level exe file to app shortcuts

- package.json
----
----
when using `yarn start` changes to typescript code are not used by the started application
run `yarn prestart` when executing `yarn start`
1. make modifications to typescript code
2. see that they are applied when using `yarn start`
----
----
----
> fix: run `prestart` befor running `start` to make sure changes in typescript are acutally being used

- electron/src/global.ts
- electron/src/preload/preload-webview.ts
With the previous version, we assumed that the decrypted string will be base65 encoded. Which is not necessarily true. We also need to be able to decrypt random bytes
> fix: Do not assume base64 encoded string when encrypting/decrypting

- electron/src/main.ts
- electron/src/runtime/lifecycle.ts
- electron/src/sso/SingleSignOn.ts
- package.json
- yarn.lock
Reverts wireapp/wire-desktop#6424
Reverts electron 23 because of an issue discovered on mac clients. 
22 will be released for now instead
> Revert "feat: electron 23 [SQSERVICES-1835]"

- bin/build-tools/lib/build-windows.ts
----
----
The `.` was not correctly escaped, causing some linters to complain. Also It still matches any 5 character file/folder that ends with `yarn`.
Use correct escaping for the backslash, that is then escaping the `.` in the regex.
Tested by verifying if the app.asar is below 75 MB and does not contain the `.yarn` folder.
----
----
----
> fix: use correct escaping in the context of regex

- electron/src/preload/preload-webview.ts
----
----
Electron webviews can close themself. If the webapp e.g. by mistake (SQSERVICES-1882) closes itself, some functionality gets disconnected. In this case shortcuts were no longer working
Removing the functionality to close itself via preload script, prevents the webapp even by mistake from closing itself.
Application should work as expected, all functionality tests must pass.
----
----
----
> fix: prevent webapp from closing itself (SQSERVICES-1919)

- electron/src/main.ts
----
----
Electron by default supports TLS connections from tls1 up to tls1.3
This PR sets the minimum version for all TLS connections to tls1.2
All automated tests must pass, regular usage does not encounter tls connections supporting only tls1 or tls1.1.
----
----
----
> feat: Set TLS 1.2 as minimum version for connections (SQCORE-652)

- electron/src/main.ts
- electron/src/menu/developer.ts
- electron/src/runtime/EnvironmentUtil.ts
This is the environments menu we currently have 
This PR will simplify this menu and only allow 3 envs:
- production
- beta (currently staging, the one used by Internal wrapper by default)
- edge (bleeding edge code straight from dev, but the courageous ones)
> fix: Improve how webapp environments are displayed in the dev menu

- electron/src/main.ts
- electron/src/runtime/lifecycle.ts
Will fix reloading the app on a different environment. 
Currently it only reload the webview without changing the environment. 
This fix will make sure that we load a new webapp URL when relaunching the app. 
User is logged in to `edge` but loading this environment doesn't show the user as logged
https://github.com/wireapp/wire-desktop/assets/1090716/c5007dc5-c7c2-4158-8a59-dea62eef3eed
The user is correctly logged in directly when switching to the `edge` environment.
https://github.com/wireapp/wire-desktop/assets/1090716/166e5bd7-849a-4010-b950-3eef1b6eab79
> fix: Allow full app reload on MacOS

- electron/src/runtime/EnvironmentUtil.ts
This allows configuring the desktop app to hit a different webapp url by editing the `init.json` file
Was broken since #7106
> runfix: Restore ability to use custom webapp url from init.json

- jenkins/deployment.groovy
Better cleanup to solve permission issues that might happen.
> build: Delete node_modules folder on start

- bin/build-tools/lib/Config.ts
- bin/build-tools/lib/commonConfig.ts
- the "Releases" link in "Help > About Wire" should link to medium instead of github by default https://wearezeta.atlassian.net/browse/WPB-5579
- End users should be able to set custom `URL-PATH` with environment variables https://wearezeta.atlassian.net/browse/WPB-4676
- make `aboutReleasesUrl` and `aboutUpdatesUrl` variables that can be determined with env variables in `getCommonConfig`
- the default env variables already exist here: https://github.com/wireapp/wire-web-config-wire/blob/master/wire-desktop/.env.defaults
> fix: make the release and information url configurable by end user (WPB-5579)

- electron/renderer/src/components/WebView/Webview.css
When you have multiple accounts logged in in the same desktop version instance, then there could be conflicts with the `<webviews>` somehow. 
This causes the sidebar to flicker when the webapp applock modal is displayed on screen. 
We used to rely on some `z-index` hack to hide all the webviews except the active one. This is probably due to the fact that `<webviews>` and `display: none` were not working properly together at some point in Electron (see https://github.com/electron/electron/issues/5110). 
We could now use the simple `display: none` to hide all the webviews that are not active anymore (and this fixes the sidebar issue, as well). 
https://github.com/wireapp/wire-desktop/assets/1090716/56e92c37-d70c-4db3-8824-d17bcb350bfa …
> fix: Address AppLock feature hiding the sidebar

- package.json
- yarn.lock
see breaking changes for:
- electron 29 https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-290
- electron 28 https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-280
> chore: Upgrade to electron 29

- electron/src/runtime/EnvironmentUtil.ts
----
----
fixes a regression introduced in #7106 
customWebappUrl is not an accurate way to determine if the app is productionEnv. Additionally, staging url has been deprecated.
> fix(env): regression with prod env not being properly read

- bin/bin-utils.ts
- electron/renderer/src/lib/util.ts
- package.json
- yarn.lock
Motivation: bump `uuidjs` from v 4.2.13 to v 5.1.0 causes problems with `jest` that are hard to resolve.
And since `uuid` has 103,276,467 weekly downloads vs `uuidjs` - 9,841, it makes sense to use `uuid`.
> chore: Replace `uuidjs` with `uuid` WPB-7240

- electron/src/preload/menu/preload-about.ts
- electron/src/preload/preload-webview.ts
- electron/src/types/globals.d.ts
- electron/src/window/AboutWindow.ts
Makes avs version optional in case the wrapper is somehow running some old version of webapp that does not share the avs version yet.
> runfix: make avs version optional

- electron/src/main.ts
To avoid a bug on hardwares that did not have GPU, we conditionally disabled hardware acceleration if `2d_canvas` was disabled. 
Problem is: this info is not available directly, it need to wait for the `gpu-info-update` event to be fired before it can be read. 
This PR makes sure the gpu info are ready before conditionally disabling hardware acceleration.
> fix: Avoid disabling hardware acceleration on every platform

- electron/src/runtime/lifecycle.ts
- electron/src/update/squirrel.ts
We don't want to clear cache every time the app is closed. Because of that we had to download all the javascript every time the app was lunched.
> runfix: don't clear cache by default when closing the app

- jenkins/windows.groovy
----
----
deletes an unnecessary test signing step to check if the key is working. it is no longer valid with our new signing method and just wastes signatures.
> chore(ci): remove test signing from build pipeline

- electron/src/main.ts
Using the `gpu-info-update` event to detect if we should disable the hardware acceleration is not a good idea since the hardware acceleration needs to be disabled **before** the app has booted. 
With this PR, we are using another technique to know whether the system has access to a GPU or not. 
This promise is resolved before the app has fully booted and it's still time to call the `app.disableHardwareAcceleration`.
> runfix: Disable hardware acceleration earlier in the boot process

- electron/src/preload/preload-webview.ts
- electron/src/types/globals.d.ts
Adds a config flag indicating whether calling popout view is supported by the desktop version,. It will be read by the webapp to decide whether to open the fullscreen view in the new window or keep it in the same window in case the new version of webapp (with calling popout view) runs in old version of the wrapper (without calling popout window support).
> chore: add flag indicating if popout calling is enabled

- yarn.lock
The last couple dependabot PRs introduced a conflict in the lockfile that this would solve
Problem introduced here https://github.com/wireapp/wire-desktop/pull/8073 (running `yarn install` on that commit 4f5e02c43a8074f8b093a256287d526d0ff6d012 results on the modified `yarn.lock`)
> chore: push correct lockfile

- package.json
- yarn.lock
Reverts wireapp/wire-desktop#8170
> Revert "chore(deps-dev): bump eslint-plugin-no-unsanitized from 4.0.2 to 4.1.0"

- .github/dependabot.yml
- package.json
- yarn.lock
This reverts commit 64ba59f2145eae0ddc0ba8d1029641b473de0370.
We're pulling the eslint config from a different repo, better revert https://github.com/wireapp/wire-desktop/pull/8174
> Revert "chore(deps-dev): bump eslint-plugin-no-unsanitized from 4.0.2 to 4.1.0 (#8174)"

- jenkins/linux.Dockerfile
Our building scripts are written for a Debian distribution, Alpine is a different distro that uses a different package manager, so our automation cannot run on the Alpine docker image for node.
Bullseye is the Debian release we were using previously (we actually can't move to Bookworm at the moment).
See bump to a new node version PR here https://github.com/wireapp/wire-desktop/pull/7077/
> runfix: provide correct node docker image for linux automation

- yarn.lock
Dependabots successive dependency updates create an issue in the lockfile, this is the correct lockfile after running `yarn install` locally
> chore: fix issues in lockfile

- electron/src/menu/system.ts
- electron/src/preload/menu/preload-context.ts
- electron/src/window/WindowUtil.ts
- package.json
- yarn.lock
Upgrade to the latest stable version of electron. https://github.com/electron/electron/releases/tag/v33.2.0
- Electron 30: https://www.electronjs.org/blog/electron-30-0
- Electron 31: https://www.electronjs.org/blog/electron-31-0
- Electron 32: https://www.electronjs.org/blog/electron-32-0
- Electron 33: https://www.electronjs.org/blog/electron-33-0
This change https://github.com/electron/electron/pull/43404 introduced in Electron 33 and backported to 32 and 31 require us to change our system menu click handler as the type of the target window changed from [BrowserWindow](https://www.electronjs.org/docs/latest/api/browser-window) to [BaseWindow](https://www.electronjs.org/docs/latest/api/base-window)
> chore: bump electron to the latest version 33.2.0 (WPB-11996)

- electron/src/menu/system.ts
- electron/src/preload/menu/preload-context.ts
- electron/src/window/WindowUtil.ts
- package.json
- yarn.lock
* chore: bump electron to 33.2.0
* chore: create helper function to send menu events to web content
* runfix: use helper function to address electron api type change
* chore: log helper function errors
- cherry-pick of the latest electron upgrade to `main`
> chore: bump electron to the latest version 33.2.0 (WPB-11996) (#8352)

- electron/src/menu/TrayHandler.ts
After a recent electron update, the dock icon will bounce relentlessly until the focus is on the window again. Previously it bounced once
https://github.com/electron/electron/pull/41391
The change in electron was made to align behaviour across platforms. 
Added a platform check to preserve the current behaviour on windows, but change the behaviour on macos to bouncing once.
> chore: fix the annoying dock bounce on macOS (WPB-14749)

- electron/src/window/WindowUtil.ts
After the electron update, the ContentMenu stopped working in many circumstances because of a failing dependency check.
This is fixed now.
> fix: contentMenu issues with inputs [WPB-14927]

- package.json
- yarn.lock
Update Electron to the latest stable major version
See release notes [here](https://releases.electronjs.org/release/v34.0.0)
> chore: update electron from 33.3.1 to 34.0.0 [WPB-15057]

- .github/workflows/pr-auto-merge.yml
Dependabot PRs have been failing to merge
[This thread](https://github.com/github/docs/issues/21930) mentions like github's cli would be expecting `GH_TOKEN` instead of `GITHUB_TOKEN`.
Unclear why it hasn't been an issue during testing the job.
Jobs currently failing
Jobs succeeding while merging to a test branch
> ci: adjust github token syntax in auto-merge job [WPB-15058]

- electron/src/window/WindowUtil.ts
Cannot resize popped out calling view in the desktop wrapper but in web app it is possible.
Remove the `minHeight` and `minWidth` constraints . This change allows popped out windows to be resized to smaller sizes.
https://github.com/user-attachments/assets/bf597106-956d-4bba-9ce8-43df32ddb24a
> fix: make popped out calling view resizable [WPB-16029]

- .github/dependabot.yml
allow Dependabot to perform dependencies updates for Electron on main and staging as well as dev
this is an alternative to cherry-picking Electron bumps to all 3 branch (backpedaling from the reverted commit from [this PR](https://github.com/wireapp/wire-desktop/pull/8533/files#diff-61c0d56ab06ca0109392dffccd6cf28b542b40fe66cdc5db85f8b6da53e9395d))
> ci: perform electron dependency updates on main, staging and dev [WPB-15058]

- bin/deploy-tools/lib/GitHubDraftDeployer.ts
- bin/deploy-tools/lib/HockeyDeployer.ts
- bin/deploy-tools/lib/deploy-utils.ts
We limit the upload size of binaries to 200MB
The MacOS binary exceeds that limit with the latest release, the `.pkg` is 207MB
This bump the maximum allowed upload size to 300MB
> ci: bump max upload size to 300MB [WPB-16532]
