- electron/main.js
Suggestion by: https://github.com/electron/electron/issues/6971#issuecomment-242803813
> Reloading the app when the render process crashes

- electron/main.js
An easy one this time. As the title says.
> Enable close to tray on Linux too

- electron/js/preload.js
> Log the version number during load

- Gruntfile.coffee
- package.json
> Revert "Downgrading electron-packager :("

- electron/js/menu/context.js
Context menu creation for conversation list is also triggered for message context menu
> Context menu tries to get conversation without ID (WEBAPP-3232)

- Gruntfile.coffee
- package.json
- yarn.lock
Throws some errors with 1.4.5.. will investigate more.
> Downgrade Electron and new builder

- package.json
- yarn.lock
> chore(package): update electron-builder to version 7.21.0

- package.json
- yarn.lock
> chore(package): update electron-builder to version 8.5.3

- electron/js/config.js
- electron/js/menu/system.js
- electron/locale/locale.js
- electron/locale/strings-it.js
- trans.py
Added italian language strings
> Added italian language

- trans.py
Related: https://github.com/wireapp/wire-webapp/pull/482
> Fix apostrophe

- electron/js/menu/context.js
To make the #207 look a bit less messy :)
> Conventions

- package.json
- yarn.lock
Not to self: Do not trust greenkeeper blindly when it comes to Electron :) https://github.com/electron/electron/releases
Reverts wireapp/wire-desktop#209
> Revert "Update electron to the latest version 🚀"

- electron/js/config.js
- electron/js/menu/system.js
- electron/locale/locale.js
- electron/locale/strings-cs.js
- electron/locale/strings-pt.js
- electron/locale/strings-sl.js
- trans.py
Related https://github.com/wireapp/wire-webapp/pull/495
> Added CS, PT, SL

- electron/js/menu/system.js
Only triggers platform-specific menu creation on triggering of createMenu function
> Webapp 3402

- package.json
- yarn.lock
> Dependencies Update

- electron/js/squirrel.js
http://electron.atom.io/docs/api/app/#appgetlocale
> Set system language on install (WEBAPP-2594)

- electron/js/lib/download.js
- electron/js/menu/tray.js
- electron/js/util.js
- electron/locale/strings-de.js
- electron/locale/strings-en.js
- electron/locale/strings.js
- electron/main.js
- tests/trayTest.js
Make use of badge counter on Linux and window flashing + icon overlay on Windows and  for unread messages
> Never miss a notification on Windows again (WEBAPP-3419)

- package.json
- yarn.lock
> chore(package): update electron-builder to version 10.12.0

- package.json
- yarn.lock
> chore(package): update electron-builder to version 10.17.3

- README.md
- package.json
Should make it a little easier for new installers.
As per #283
> Added build commands, updated README accordingly

- package.json
- yarn.lock
> chore(package): update electron-builder to version 11.3.0

- electron/js/menu/context.js
Fixes #296.
Works with multi-line text and code blocks.
> #296 Implement 'Copy' context menu functionality

- electron/js/config.js
- electron/js/menu/system.js
- electron/locale/locale.js
- electron/locale/strings-da.js
- trans.py
https://github.com/wireapp/wire-webapp/pull/637
> 🇩🇰 Added Danish 🇩🇰

- electron/js/menu/tray.js
- electron/locale/strings-cs.js
- electron/locale/strings-da.js
- electron/locale/strings-de.js
- electron/locale/strings-en.js
- electron/locale/strings-es.js
- electron/locale/strings-fi.js
- electron/locale/strings-fr.js
- electron/locale/strings-hr.js
- electron/locale/strings-it.js
- electron/locale/strings-pt.js
- electron/locale/strings-ro.js
- electron/locale/strings-ru.js
- electron/locale/strings-sl.js
- electron/locale/strings-tr.js
- electron/locale/strings-uk.js
- electron/locale/strings.js
> Localize tray icon

- electron/js/config.js
- electron/js/menu/system.js
- electron/locale/locale.js
- electron/locale/strings-hu.js
- trans.py
https://github.com/wireapp/wire-webapp/pull/672
> 🇭🇺  Add Hungarian 🇭🇺

- package.json
> chore(package): update electron-builder to version 11.6.1

- electron/js/preload.js
- electron/js/squirrel.js
- electron/main.js
Related to https://github.com/wireapp/wire-webapp/pull/696
> Identify wrapper as source of update

- package.json
> chore(package): update electron-builder to version 12.2.2

- .gitignore
> Added .vscode to gitignore

- package.json
crashing on exit with 1.5.0 :/
> Electron 1.4.15

- package.json
> chore(package): update electron-builder to version 13.8.0

- package.json
> chore(package): update electron-builder to version 13.8.2

- electron/package.json
> Change package name to wire-desktop

- electron/js/menu/system.js
May the Alt key rest peacefully!
> Add menu toggle on Linux (addresses #476)

- electron/main.js
- package.json
> Downgrade Electron to 1.4.15

- electron/js/config.js
- electron/js/menu/system.js
- electron/locale/locale.js
- electron/locale/strings-sk.js
- trans.py
https://github.com/wireapp/wire-webapp/pull/837
> 🇸🇰 Add Slovak 🇸🇰

- bin/win-prod-s3-deploy.py
- bin/win-s3-deploy.py
> Missing variables

- electron/html/about.html
- electron/js/about.js
- electron/js/preload.js
- electron/locale/strings-cs.js
- electron/locale/strings-da.js
- electron/locale/strings-de.js
- electron/locale/strings-en.js
- electron/locale/strings-es.js
- electron/locale/strings-fi.js
- electron/locale/strings-fr.js
- electron/locale/strings-hr.js
- electron/locale/strings-hu.js
- electron/locale/strings-it.js
- electron/locale/strings-pt.js
- electron/locale/strings-ro.js
- electron/locale/strings-ru.js
- electron/locale/strings-sk.js
- electron/locale/strings-sl.js
- electron/locale/strings-tr.js
- electron/locale/strings-uk.js
- electron/locale/strings.js
- electron/main.js
For translations: https://crowdin.com/project/wire-cs
> Showing more stuff in About (WEBAPP-3780)

- electron/js/config.js
- electron/js/menu/system.js
- electron/locale/locale.js
- electron/locale/strings-hu.js
- electron/locale/strings-lt.js
- electron/locale/strings-pt.js
- electron/locale/strings-ro.js
- electron/locale/strings-ru.js
- electron/locale/strings-sk.js
- electron/locale/strings-sl.js
- electron/locale/strings-tr.js
- electron/locale/strings-uk.js
- trans.py
https://github.com/wireapp/wire-webapp/pull/1022
> Add Lithuanian

- electron/package.json
> Update electron-build-env to 0.2.0

- electron/js/preload.js
Needs https://github.com/wireapp/wire-webapp/pull/1125
> Publish amplify events when joining calls

- package.json
> Update electron-builder and electron-packager

- package.json
> chore(package): update electron-winstaller to version 2.6.3

- electron/main.js
- electron/renderer/src/components/Webviews.js
- electron/renderer/src/index.js
- electron/renderer/static/webview-preload.js
we might wanna move the code into a seperate module that can be required from the main and renderer process
> feat: per webview logging

- bin/linux-prod-s3.py
- bin/repo/linux-prod-repo.sh
Add `InRelease` file for some Linux distributions.
Fixes https://github.com/wireapp/wire-desktop/issues/771.
> fix: Add InRelease file

- electron/js/menu/system.js
- electron/renderer/src/components/Webview.js
- electron/renderer/src/components/Webviews.js
- electron/renderer/static/webview-preload.js
Relates to https://github.com/wireapp/wire-webapp/pull/1504
> revert: Update shortcut for search (from #710)

- electron/main.js
> fix: Add title to about window

- electron/js/menu/developer.js
Probably a bad hack, but very useful.
> Add devtools submenu with entries for sidebar and accounts

- bin/github_draft.py
The upload should not be done as multipart file upload.
> fix: Automatic Github draft upload

- electron/locale/locale.js
- electron/locale/strings-et.js
- trans.py
https://github.com/wireapp/wire-webapp/pull/1806
> feat: Add Estonian translations

- package.json
> chore(package): update prettier to version 1.8.2

- package.json
> chore(package): update grunt-git to version 1.0.9

- electron/js/lib/settings.js
> fix: Ensure content of configuration on persistation

- electron/renderer/src/components/Webviews.js
> fix: Disable background throttling in webview

- electron/package-lock.json
- electron/package.json
- electron/rebuild-native-modules.js
> Update libsodium-neon and disable PIE

- Gruntfile.js
- electron/package-lock.json
- package-lock.json
- package.json
- webpack.config.js
> refactor: Update webpack to 4.6.0

- bin/linux-checksums.sh
- bin/repo/linux-prod-repo.sh
> chore: Create private-keys-v1.d directory to fix issue with gpg2

- Gruntfile.js
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#electron-packager-api
> chore: Use Promise flavor of electron-packager

- electron/js/appInit.js
> fix: Add path import for portable flag

- bin/repo/linux-prod-repo.sh
This adds a function `_cleanup()` which will always be called on exit, even on error or when a user or the system kills the script.
> feat: Add exit trap

- electron/renderer/static/webview-preload.js
This is the second step of https://github.com/wireapp/wire-webapp/pull/4552
> fix: Load the full (clear|set)Immediate polyfill needed by the webapp

- Gruntfile.js
This is not a must, I just figured it would be nice to have the objects sorted. :slightly_smiling_face:
> chore: Sort objects in Gruntfile

- electron/js/environment.js
- electron/main.js
This PR will
* log the hostname when a SSL connection failed
* use the verification result for validating SSL connections
> fix: Check certificate verification result

- electron/renderer/static/webview-preload.js
- electron/src/js/preload-sso.ts
Follow-up to https://github.com/wireapp/wire-desktop/pull/1901.
> fix: Remove remaining imports from 'js/lib'

- electron/package.json
- electron/src/main.ts
- electron/src/util/LogFactory.ts
- electron/yarn.lock
- yarn.lock
Log statements from the main process will be written to:
- `%APPDATA%\Wire\logs\electron.log`
- `%APPDATA%\WireInternal\logs\electron.log`
The `electron.log` file will be renamed to `electron.old` when relaunching the app.
> feat: Write Electron log statements to disk

- .travis.yml
- linux.Dockerfile
- macOS.Jenkinsfile
- windows.Jenkinsfile
[Release Notes for 8.13.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.13.0)
>  chore: Update Node.js to 8.13.0

- linux.Dockerfile
- macOS.Jenkinsfile
- windows.Jenkinsfile
See https://nodejs.org/en/blog/release/v8.14.0/
> chore: Update Node.js to 8.14.0

- .gitattributes
- .gitignore
- bin/github_draft.py
- bin/linux-checksums.sh
- bin/macos-checksums.sh
- linux.Jenkinsfile
- macOS.Jenkinsfile
This fixes https://github.com/wireapp/wire-desktop/issues/1944.
> chore: Sign .tar.gz sources with Jenkins

- bin/linux-checksums.sh
Follow-up to #1947 
Fixes https://github.com/wireapp/wire-desktop/issues/1944#issuecomment-449444326
> Create a detached signature for the sources archive

- electron/package.json
- electron/yarn.lock
- package.json
> chore: Use electron-rebuild for native modules

- Gruntfile.js
- electron/src/js/environment.ts
- electron/src/js/lifecycle.ts
If we don't run the update check, the installation will not complete.
> fix: Revert update switch

- Gruntfile.js
- electron/src/lib/CoreProtocol.ts
Manually tested on Debian 9.7 + Gnome.
> runfix: Enable SSO link for Linux

- electron/src/js/about.ts
- electron/src/lib/SingleSignOn.ts
- electron/src/main.ts
Follow-up to https://github.com/wireapp/wire-desktop/pull/2215.
> fix: Preload file paths

- electron/renderer/static/webview-preload.js
> fix: Path for context menu file

- electron/src/js/about.ts
> fix: Path for about preload file

- electron/src/lib/openGraph.ts
Connected to https://github.com/wireapp/wire-webapp/pull/6066.
> chore: Bubble up OpenGraph fetching errors to the webapp

- electron/src/interfaces/main.ts
- electron/src/main.ts
- electron/src/runtime/lifecycle.ts
- electron/src/update/Squirrel.ts
- jenkins/windows.groovy
- package.json
- yarn.lock
This PR reverts major changes in 5b2e1af, 1ca3654 and d43b11d and keeps only introduced fixes.
> fix: Revert Squirrel related changes

- electron/src/lib/SingleSignOn.ts
- electron/src/lib/webViewFocus.ts
- electron/src/renderer/menu/preload-about.ts
This PR will
* remove a few unnecessary `any`
* rename unused variables to `_`
* align some imports
Note: There is no behavior change.
> chore: Small typing fixes

- .copyconfigrc.js
- electron/wire.json
- jenkins/linux.groovy
- jenkins/macOS.groovy
- jenkins/windows.groovy
- package.json
- yarn.lock
Follow-up to https://github.com/wireapp/wire-desktop-packages/pull/424
> runfix: Read version from wire.json, update build-tools

- electron/renderer/src/actions/index.js
- electron/renderer/src/components/App.jsx
- electron/renderer/src/components/Sidebar.jsx
Left-over from https://github.com/wireapp/wire-desktop/pull/2491.
> runfix: Import config for maximumAccounts

- electron/renderer/src/components/Sidebar.jsx
Follow-up to https://github.com/wireapp/wire-webapp/pull/6490
> chore: Use z.team variable from WebApp

- electron/src/lib/CertificateVerifyProcManager.ts
- package.json
- yarn.lock
Follow-up to https://github.com/wireapp/wire-desktop-packages/pull/529.
> fix: Always check for error messages when pinning

- .github/issue_template.md
- electron/renderer/static/webview-preload.js
- electron/src/lib/CertificateVerifyProcManager.ts
- electron/src/lib/CoreProtocol.ts
- electron/src/lib/LocalAccountDeletion.ts
- electron/src/lib/download.ts
- electron/src/lib/openGraph.ts
- electron/src/locale/locale.ts
- electron/src/main.ts
- electron/src/renderer/preload.ts
- electron/src/settings/SchemaUpdater.ts
- electron/src/update/Squirrel.ts
- package.json
```
$ wire-desktop --version
3.9.2895
```
> feat: Add version flag, streamline logger

- jenkins/macOS.groovy
- jenkins/windows.groovy
Preparation for the new process. Will fix the current smoke trigger issue.
> chore: Use webapp master environment in Jenkins

- electron/src/interfaces/main.ts
- electron/src/menu/developer.ts
- electron/src/menu/system.ts
- electron/src/renderer/menu/context.ts
This fixes https://github.com/wireapp/wire-desktop/issues/808
> fix: Add alt shortcuts for main menus

- .travis.yml
See https://benlimmer.com/2019/01/14/travis-ci-xvfb/
> fix: Use Xenial in Travis

- electron/css/proxy-prompt.css
- electron/html/proxy-prompt.html
> feat: Improve proxy prompt

- electron/src/main.ts
This fixes https://github.com/wireapp/wire-desktop/issues/3033.
> fix: Portable path

- electron/src/lib/openGraph.ts
Backported https://github.com/wireapp/wire-desktop/pull/3001 to Electron 4.
> fix: Speed up link preview generation (WEBAPP-6415) (backport)

- electron/src/main.ts
Backported https://github.com/wireapp/wire-desktop/pull/3153 to Electron 4.
> feat: Add crash log (backport)

- electron/src/logging/getLogger.ts
- electron/src/logging/loggerUtils.ts
- electron/src/main.ts
- electron/src/menu/developer.ts
- package.json
Backported https://github.com/wireapp/wire-desktop/pull/3125 to Electron 4.
> feat: Add developer option to send logs via email (WEBAPP-6493) (backport)

- electron/src/logging/loggerUtils.ts
- electron/src/menu/developer.ts
- package.json
- yarn.lock
> runfix: Open logs folder if logs can't be send via email

- .copyconfigrc.js
- electron/src/main.ts
- electron/src/window/AboutWindow.ts
Related: https://github.com/wireapp/wire-desktop/issues/3170
> fix: Set correct window icon

- electron/src/lib/openGraph.ts
Before we were returning a `Promise` with a new `Promise` somewhere inside, now the function is `async` and only the `request` part is wrapped inside a `Promise` because we need to react on the emitted events.
Best viewed [without whitespace changes](https://github.com/wireapp/wire-desktop/pull/3204/files?w=1).
> refactor: Flatten promises in openGraph parsing

- electron/src/sso/SingleSignOn.ts
Backported https://github.com/wireapp/wire-desktop/pull/3310 to Electron 5.
> fix: check if SSO URL is null and simplify cookie copy (backport)

- electron/src/locale/locale.ts
Allow users to select the Chinese
> fix: Adding support for Chinese

- electron/src/lib/openGraph.ts
> fix: Use custom User-Agent for Twitter link previews (WEBAPP-6664)

- electron/src/window/AboutWindow.ts
This closes https://github.com/wireapp/wire-desktop/issues/3803.
> feat: Don't set about window to be always on top (WEBAPP-7045)

- electron/renderer/src/actions/index.js
This allows new WebApp features regarding account management to be sent to the wrapper even though we don't know about them in the wrapper yet.
> feat: Allow unknown account data

- electron/src/main.ts
- electron/src/renderer/preload-sso.ts
- electron/src/sso/SingleSignOn.ts
See https://www.electronjs.org/releases/stable#9.2.0 and https://github.com/electron/electron/pull/24114
> feat: Enable worldSafeExecuteJavaScript

- bin/build-tools/build-cli.ts
- bin/build-tools/build-linux-desktop-file.ts
- bin/build-tools/lib/Config.ts
- bin/build-tools/lib/build-linux.ts
- bin/build-tools/lib/build-macos.ts
- bin/build-tools/lib/build-windows-installer.ts
- bin/build-tools/lib/build-windows.ts
This closes https://github.com/wireapp/wire-desktop/issues/4920.
> feat(build-tools): Build Linux Desktop file

- .github/workflows/semantic-commit-lint.yml
- .prettierignore
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQPIT-769" title="SQPIT-769" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10818&avatarType=issuetype" />SQPIT-769</a>  Add semantic linting of PR titles to relevant client repository
</td></table>
<br />
----
----
We want to ensure that PR titles should follow semantic commit rules
Add the semantic commit linter workflow from the Wire's .github repo
N/A
----
----
----
1. E.g. `feature(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.
> ci: Add semantic commit lint of PR titles SQPIT-769

- app-config/package.json
> chore: update config version

- package.json
- yarn.lock
> chore: Bump electron from 18.2.0 to 18.3.2

- electron/src/main.ts
- electron/src/sso/SingleSignOn.ts
- electron/src/window/AboutWindow.ts
> fix: prevent connections by electron on link clicks (SQCORE-1348)

- bin/build-tools/lib/build-linux.ts
- bin/build-tools/lib/build-macos.ts
- bin/build-tools/lib/build-windows.ts
- bin/build-tools/lib/commonConfig.ts
- electron/src/main.ts
- electron/src/window/AboutWindow.ts
- electron/src/window/ProxyPromptWindow.ts
- package.json
- yarn.lock
----
----
Electron Supports fuses for enhanced security (see also https://www.electronjs.org/docs/latest/tutorial/fuses)
Flip fuses after the app binary is created.
Each binary for each platform needs to be tested, whether it still runs or not.
----
----
----
> flip electron fuses during app build process (FS-997)

- electron/src/main.ts
https://www.electronjs.org/docs/latest/api/app#event-gpu-process-crashed-deprecated mentions the gpu-process-crashed event handler is deprecated:
> Deprecated: This event is superceded by the child-process-gone
> event which contains more information about why the child process
> disappeared.
> It isn't always because it crashed. The killed boolean can be replaced
> by checking reason === 'killed' when you switch to that event.
There's been some reports of people with AMD GPUs not beeing able to log in with wire-desktop > 3.29.2997 (WEBAPP-7162).
Whenever the event occurs, the user is thrown back to the login screen, but unable to login, as they're "already logged in".
This updates the handler to use child-process-gone, and only log event and details, rather than invoking `main.reload()`, …
> fix: replace gpu-process-crashed with child-process-gone event handler

- electron/src/main.ts
- electron/src/sso/SingleSignOn.ts
- package.json
- yarn.lock
* prevent creation of new windows from SSO Windows
* set more restrictive defaults in Window Creation
* update to latest electron 22.x (23.x works as well)
* did some cleanup of unused/obsolete variables
> Updates for feat/electron22

- electron/renderer/index.html
----
----
Having `object-src` set to `'self'` allows in theory to load <embed>, <applet>, or <object> tags.
Setting object-src` set to `'none'` disables them completely.
As Wire does not make use of these tags, this can be safely disabled.
This should not have effects on the application. All integrations tests must succeed
----
----
----
> feat: Harden CSP for electron renderer (SQSERVICES-1989)

- package.json
> runfix: Rename product name

- electron/src/lib/LocalAccountDeletion.ts
- electron/src/preload/preload-app.ts
- electron/src/runtime/EnvironmentUtil.ts
----
----
Deletes current logs when a user removes an account to remove history of the deleted user from the computer.
> fix: remove logs for deleted accounts, remove unused endpoints [WPB-1523]

- .github/workflows/dependabot-auto-merge.yml
Will enable auto merge of minor and patch level dependabot update PR
> chore: Enable auto-merge of dependabot PR

- electron/src/main.ts
- package.json
- yarn.lock
Electron 26 has quite a lot of grey screen of death appearing at random times. 
This is an attempt to test electron 27 and see if it fixes those crashes
This will also improve the logs of the app
> chore: upgrade to electron 27 + improve crash handling

- electron/src/main.ts
- electron/src/runtime/EnvironmentUtil.ts
----
----
Updates DL path to fix some issues related to paths not being available outside of the user menu
> Feat: Windows download location updates

- .github/dependabot.yml
- .github/workflows/download_translations.yml
----
----
updating some pipelines to improve translation upload and to update actions dependencies.
> chore: some updates to pipelines

- electron/wire.json
- jenkins/windows.groovy
- package.json
----
----
- Implement new certification method
- increment desktop version
> feat: pipeline cert update [WPB-7048]

- .github/dependabot.yml
- package.json
- yarn.lock
Reverts wireapp/wire-desktop#7816
> Revert "build(deps): bump electron-dl from 3.5.2 to 4.0.0"

- electron/src/calling/PictureInPictureCall.ts
- electron/src/main.ts
- electron/src/sso/SingleSignOn.ts
- electron/src/window/WindowUtil.ts
This PR adds support for Picture-In-Picture calling view PoC.
> feat: picture in picture calling view PoC

- app-config/package.json
- bin/build-tools/lib/build-linux.ts
- package.json
- yarn.lock
Merge the latest dev into staging.
We intend to release a Linux internal version including this change https://github.com/wireapp/wire-desktop/pull/8240
> chore: merge dev into staging

- electron/src/calling/PictureInPictureCall.ts
- electron/src/window/WindowUtil.ts
> feat: hide menu on calling pop out window [WPB-10680]

- electron/wire.json
- package.json
Increment app version prior to release
See latest bump here https://github.com/wireapp/wire-desktop/commit/cf65edb5981be370f3284555512696175099e234
> chore: increment app version

- .github/workflows/cherry-pick-electron-bumps.yml
testing auto-merge to desktop repo
> chore: test test test

- .github/workflows/cherry-pick-electron-bumps.yml
> chore: no matching words

- .github/workflows/cherry-pick-electron-bumps.yml
> chore: testing one matching word

- .github/workflows/cherry-pick-electron-bumps.yml
> chore: test testing ci all matching

- .github/workflows/cherry-pick-electron-bumps.yml
> chore: test one matching

- jenkins/linux.Dockerfile
----
----
With this change the linux version of the desktop app can be build on a new provisioned jenkins node.
> build: Update node version and fix issues with permissions
